dist: trusty
language: c
compiler:
  - gcc

before_install:
  - test -n $CC && unset CC
  - chmod +x bootstrap
  
addons:
  sonarcloud:
    organization: "mmacala"
    token:
      secure: "jCDwj1Vo0yDo0zmpnlG2cBFAp4BxK4Kp9gj+k3k9mZMecxofg8aa9+LQ43VANcaxybc5mmJ+DE2BVTxkUi1JVeY0dYOtUd6lf3Iec2pMFepFJw1UzOVy7iSqmb1I1XTE6l1nICFM6j0De7oHXT93GwNdr0ur1HRioT4P6y7TP6sPsaaN/p+otuRBZ5YINDJ6ERgcXDn///h/ut/ldJFJUFgmZ1GB6OFWYtdNdSUNH/8PlWqwjCwH0jLGZWUiedBYaIseDdbuY5mDygAMO+yQu1DPKaNYB5NjVDGWhuv5gyW9VX9vzDysY/A2tir63CxIcbhFPPIRs8KmIEdzp7YL1aslubl6t7zvPipOFp6GFSB412nrb+VmaX/vbfXftuKDHGJdv0eiSiomT0IxCnKNu4EDugP1uAt43yMF6ImtdWgiPel1dvcH91ipiv6lYVcHr3WqiXfHQNdI8ZzKml3UlPC952gxT54AgtENu2Xh4SvSP5K7DinIuJck2dTjD+bGadFX6NYz/tCKFKTRkwc0DlHDn+5bsXv+5xorvk42hkNDvHgpZ1gTC5wdHVaHSk77vIdc4d4EZnaJv9SakmhtYuZPg/OL+6VKITmbs4ecxd94OcaqcHmB4T8iad270IMdfcV5hGKPGpnYb7zAC2lvGvJA1+qcCnT9TMprwJsXoSU="


script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output ./bootstrap
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -x -Dsonar.cfamily.build-wrapper-output=bw-output
